--------------------------------------------------------
--  File created - Monday-August-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTACT_MESSAGES
--------------------------------------------------------

  CREATE TABLE "FALKOM_ADMIN"."CONTACT_MESSAGES" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EVENT_TYPE" VARCHAR2(100 BYTE), 
	"MESSAGE" CLOB, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "FALKOM_ADMIN"."EVENTS" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(10,0), 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EVENT_NAME" VARCHAR2(150 BYTE), 
	"EVENT_TYPE" VARCHAR2(100 BYTE), 
	"PACKAGE_NAME" VARCHAR2(50 BYTE), 
	"PACKAGE_ITEMS" CLOB, 
	"EVENT_DATE" DATE, 
	"LOCATION" VARCHAR2(200 BYTE), 
	"GUEST_COUNT" NUMBER(10,0) DEFAULT 0, 
	"EVENT_DESCRIPTION" CLOB, 
	"SPECIAL_REQUEST" CLOB, 
	"FILES" CLOB, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Pending', 
	"ADMIN_REMARKS" CLOB, 
	"SUBMITTED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PACKAGE_ITEMS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EVENT_DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SPECIAL_REQUEST") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FILES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ADMIN_REMARKS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GALLERY
--------------------------------------------------------

  CREATE TABLE "FALKOM_ADMIN"."GALLERY" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SRC" CLOB, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("SRC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table PACKAGE_REQUIREMENTS
--------------------------------------------------------

  CREATE TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EVENT_TYPE" VARCHAR2(100 BYTE) DEFAULT 'ALL EVENT TYPES', 
	"PACKAGE_TYPE" VARCHAR2(50 BYTE), 
	"REQUIREMENT_ITEM" VARCHAR2(400 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "FALKOM_ADMIN"."SERVICES" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(150 BYTE), 
	"DESCRIPTION" CLOB, 
	"APPEARANCE" VARCHAR2(30 BYTE) DEFAULT 'icon', 
	"IMAGE_URL" CLOB, 
	"ICON_NAME" VARCHAR2(50 BYTE) DEFAULT 'Sparkles', 
	"SECTION" VARCHAR2(30 BYTE) DEFAULT 'cards', 
	"IS_DEFAULT" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("IMAGE_URL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "FALKOM_ADMIN"."USERS" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"PACKAGE" VARCHAR2(50 BYTE) DEFAULT '—', 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'client', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"PHONE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FALKOM_ADMIN.CONTACT_MESSAGES
SET DEFINE OFF;
REM INSERTING into FALKOM_ADMIN.EVENTS
SET DEFINE OFF;
Insert into FALKOM_ADMIN.EVENTS (ID,USER_ID,FULL_NAME,EMAIL,PHONE,EVENT_NAME,EVENT_TYPE,PACKAGE_NAME,EVENT_DATE,LOCATION,GUEST_COUNT,STATUS,SUBMITTED_AT) values (1,1,'moaiad','moaiadabu5@gmail.com','0785553388','gradution party','GRADUATIONS','GOLD',to_date('22-SEP-26','DD-MON-RR'),'4 seoson hotel',55,'Pending',to_timestamp('24-AUG-26 08.41.27.277000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into FALKOM_ADMIN.GALLERY
SET DEFINE OFF;
REM INSERTING into FALKOM_ADMIN.PACKAGE_REQUIREMENTS
SET DEFINE OFF;
REM INSERTING into FALKOM_ADMIN.SERVICES
SET DEFINE OFF;
REM INSERTING into FALKOM_ADMIN.USERS
SET DEFINE OFF;
Insert into FALKOM_ADMIN.USERS (ID,USERNAME,EMAIL,PASSWORD_HASH,PACKAGE,ROLE,CREATED_AT,PHONE) values (1,'moaiad','moaiadabu5@gmail.com','$2b$10$k7shlj564ZRouop/VHPffeUNSXbwgUZC7HUmEszBuHfUTVn1rMMrC','—','client',to_timestamp('24-AUG-26 08.37.54.773000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into FALKOM_ADMIN.USERS (ID,USERNAME,EMAIL,PASSWORD_HASH,PACKAGE,ROLE,CREATED_AT,PHONE) values (2,'admin','moaiad.mohammad.2004@gmail.com','$2b$10$8jzfmoRWU/8XCdQ9qaCl/e7MZhZvzXcjQLjFHQiXvaCQUpyHm9sBK','—','admin',to_timestamp('24-AUG-26 08.42.32.053000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null);
--------------------------------------------------------
--  DDL for Index SYS_C008343
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008343" ON "FALKOM_ADMIN"."CONTACT_MESSAGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008337
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008337" ON "FALKOM_ADMIN"."EVENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_EVENTS_USER_ID
--------------------------------------------------------

  CREATE INDEX "FALKOM_ADMIN"."IDX_EVENTS_USER_ID" ON "FALKOM_ADMIN"."EVENTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_EVENTS_STATUS
--------------------------------------------------------

  CREATE INDEX "FALKOM_ADMIN"."IDX_EVENTS_STATUS" ON "FALKOM_ADMIN"."EVENTS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008347
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008347" ON "FALKOM_ADMIN"."GALLERY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GALLERY_CATEGORY
--------------------------------------------------------

  CREATE INDEX "FALKOM_ADMIN"."IDX_GALLERY_CATEGORY" ON "FALKOM_ADMIN"."GALLERY" ("CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008361
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008361" ON "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PKG_REQS_SEARCH
--------------------------------------------------------

  CREATE INDEX "FALKOM_ADMIN"."IDX_PKG_REQS_SEARCH" ON "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" ("EVENT_TYPE", "PACKAGE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008355
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008355" ON "FALKOM_ADMIN"."SERVICES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SERVICES_SECTION
--------------------------------------------------------

  CREATE INDEX "FALKOM_ADMIN"."IDX_SERVICES_SECTION" ON "FALKOM_ADMIN"."SERVICES" ("SECTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008323
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008323" ON "FALKOM_ADMIN"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008324
--------------------------------------------------------

  CREATE UNIQUE INDEX "FALKOM_ADMIN"."SYS_C008324" ON "FALKOM_ADMIN"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONTACT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."CONTACT_MESSAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."CONTACT_MESSAGES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."CONTACT_MESSAGES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."CONTACT_MESSAGES" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."CONTACT_MESSAGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("PACKAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("GUEST_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" ADD CHECK (status IN ('Pending', 'Accepted', 'Rejected')) ENABLE;
  ALTER TABLE "FALKOM_ADMIN"."EVENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GALLERY
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."GALLERY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."GALLERY" MODIFY ("SRC" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."GALLERY" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."GALLERY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACKAGE_REQUIREMENTS
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" MODIFY ("PACKAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" MODIFY ("REQUIREMENT_ITEM" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" ADD CHECK (package_type IN ('SILVER', 'GOLD', 'DIAMOND')) ENABLE;
  ALTER TABLE "FALKOM_ADMIN"."PACKAGE_REQUIREMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."SERVICES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" MODIFY ("APPEARANCE" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" MODIFY ("SECTION" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" MODIFY ("IS_DEFAULT" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" ADD CHECK (appearance IN ('icon', 'customIcon', 'photo', 'none')) ENABLE;
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" ADD CHECK (section IN ('cards', 'eventTypes')) ENABLE;
  ALTER TABLE "FALKOM_ADMIN"."SERVICES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."USERS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "FALKOM_ADMIN"."USERS" ADD CHECK (role IN ('admin', 'client')) ENABLE;
  ALTER TABLE "FALKOM_ADMIN"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FALKOM_ADMIN"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "FALKOM_ADMIN"."EVENTS" ADD CONSTRAINT "FK_EVENTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "FALKOM_ADMIN"."USERS" ("ID") ON DELETE SET NULL ENABLE;
